project:
  type: book

book:
  title: Title for this example thesis
  author: 
    - name: Author Authorsson
      orcid: 0000-0001-8715-9XXX
      url: https://www.his.se/test
      email: author.authorsson@his.se
      affiliations:
        - name: University of Skövde
          department: School of Engineering Science
          address: Högskolevägen BOX 152
          city: Skövde
          postal-code: 541 30
          url: https://www.his.se
        - name: Another company
          url: https://www.google.com
  date: 2023-09-16
  abstract: Testing abstract
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - intro.qmd
    - part: "Background"
      chapters:
        - background.qmd
        - summary.qmd

bibliography: references.bib

format:
  his-pdf:
    keep-tex: true
    classoption:
      - english
      - cover
      - final
  his-html: default

his-metadata:
  coverimage: foto.jpg
  coverphoto: face.jpg
  publicationtype: dissertation
  sammanfattning: Abstract in Swedish
  shortabstract: Summary on the back of the thesis
  fullarticles: |
    \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=-][\href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{\ccbyncnd}]{fischer2017doctoraldissertationmanual}{manual.pdf}
    \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1][\copyright{} 2018 University of Skövde. Reprinted, with permission, from]{fischer2017doctoraldissertationmanual}{manual.pdf}
    \fullarticle[scale=.7,trim={0mm 5mm 0mm 5mm},pages=1][Reprinted from][with permission from University of Skövde.]{fischer2017doctoraldissertationmanual}{manual.pdf}
  acronyms: |
    \newacronym{moo}{MOO}{Multi-Objective Optimization}
    \newacronym{sbo}{SBO}{Simulation-Based Optimization}
    \newacronym{ai}{AI}{Artificial Intelligence}
    \newacronym{doe}{DOE}{Design of Experiments}
  ownpublications: |
    \authorspublication{fischer2017doctoraldissertationmanual}
    \authorspublication[Design, manuscript preparation, review]{fischer2017doctoraldissertationmanual}
